# Generated by Django 4.1.3 on 2023-11-17 07:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tic_tac_toe", "0003_alter_board_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="previous",
            field=models.CharField(default="O", max_length=1),
        ),
    ]
